### ISSUE TITLE
User script

### ISSUE THREAD

**Issue by 1nner-Peace** [mrbrainz/Soundcloud-Stream-Manager#1]
Good day,

first of all, I want to thank you for your work. I was wondering if you would like to make your script accessible as user script on a website like [greasyfork.org](https://greasyfork.org). In case you don't know user scripts are code written in Javascript which can be injected into a page with an add-on like [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/).
Best wishes!

**Comment by 1nner-Peace** [comment]
[I created it for you.](https://greasyfork.org/en/scripts/38966-soundcloud-stream-manager-by-mr-brainz) If you want me to remove it, just let me know.

**Comment by mrbrainz** [comment]
Hi. Thanks. No problem with you doing this. What happens if I update the code? Do you need to update this code?

Thanks

**Comment by 1nner-Peace** [comment]
Only if you change the code of your bookmarklet itself.
